apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatify-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beatify-api-pods
  template:
    metadata:
      labels:
        app: beatify-api-pods
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ecr-credentials
      containers:
        - name: beatify-api
          image: 986080617761.dkr.ecr.eu-west-1.amazonaws.com/beatify-api:v1.0
          env:
            - name: "JAMENDO_API_URL"
              valueFrom:
                secretKeyRef:
                  name: "app-enviroment-variables"
                  key: "JAMENDO_API_URL"
            - name: "JAMENDO_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  name: "app-enviroment-variables"
                  key: "JAMENDO_CLIENT_ID"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "2Gi"
          ports:
            - containerPort: 3000
